### ISSUE TITLE
Multiple Cadence client issues

### ISSUE THREAD

**Issue by johncburns1** [nforgeio/neonKUBE#648]
All Test_EndToEnd tests pass when `Debug == true` in the `CadenceSettings` used to initialize the `CadenceFixture`.  Although when `Debug == false` and `LogLevel == Debug`, some of the tests fail unexpectedly.  I think it might be a latency thing.  Because ignoring `PingAttack` helps the issue a bit.  I do not think that this is a cadence-proxy issue because the only thing the `Debug` option is used for is deciding whether or not messages should be logged to Stdout.  That being said, I have not been able to identify the issue.  I can do a deeper dive in a little bit.

**Comment by jefflill** [comment]
I'll bet this is the multiple-client issue I've been debugging.

**Comment by jefflill** [comment]
The `Test_MultiClient` tests always fail.  This happens due to a decision task timeout.

I looked into this further by setting a breakpoint on **line 138**:
```
Assert.Equal("WF1 says: Hello Jack!", await stub1.HelloAsync("Jack"));
```
and then select the ``Test_MultiClient`` test in VS Test Explorer and then run the test case.

I'm seeing the **Simultaneous** test run first and pass and then the **Connect_Twice** test runs and the breakpoint is hit.  Then I press F5 to continue running.

What I'm seeing from the cadence/cadence-proxy logs is:

1. The .NET side sends a `WorkflowExxecutionRequest` to **cadence-proxy**
2. **cadence-proxy* ** submits the request to Cadence.
3. Cadence schedules the workflow to run on our client.
4. **cadence-proxy** sees its workflow function being called.
5. ...and then we pretty much hang

I never see a `WorkflowInvokeRequest` for the workflow.

**Comment by jefflill** [comment]
**UPDATE:** After looking at this again, I am seeing the `WorkflowInvokeRequest` but it has `ClientId=1` which refers to the first of the two clients created by the **Simultanious** test.  These clients no longer exist at this time.  I was expecting `ClientId=3` for the first client created by the **Connect_Twice** test.

**Comment by johncburns1** [comment]
FIXED.  Resolved this issue by adding the `ClientId` workflow parameter.  This makes it so the `ClientId` used to send the `WorkflowInvokeRequest` matches the `ClientId` used in the `WorkflowExecuteRequest`.

**Comment by johncburns1** [comment]
Do you anticipate this being an issue for `SignalSubscribe` and `QueryHandler`?

**Comment by jefflill** [comment]
Yes, the `QueryInvokeRequest` and `SignalInvokeRequest` messages should include the client ID from the requests that registered query and signal.

**Comment by johncburns1** [comment]
This issue still stands.  I think we have figured out what the issue is, but need to make sure that behavior is understood.

**Comment by jefflill** [comment]
To summarize:

* It appears that the GOLANG Cadence client appears to record workflow/activity registrations in global process state such the these registrations are still present even after workers have been stopped and Cadence cluster connections are closed.

* Opening subsequent client connections and attempting to re-register workflows/activities will fail.

This is probably going to occur very rarely in real-life because most folks will start Cadence workers and then leave them run.  They won't typically have multiple Cadence connections.  We're encountering this due to how our unit tests work.

I think I may be able to workaround this for the unit tests.  We'll track this here: #668
